---
title: "Crab.capstone-qpcr"
author: "Claudia Mateo"
date: "6/25/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
install.packages("dplyr")
library("dplyr")
install.packages("https://cran.r-project.org/bin/macosx/contrib/4.1/colorspace_2.0-2.tgz", repos=NULL) #install 'colorspace'
install.packages("ggplot2") #no package called 'colorspace'
library("ggplot2")
```

```{r files}
qpcr <- read.csv("/Users/crpenney/Desktop/crab-capstone/data/hematqpcr_crabRNA.csv")
head(qpcr)
```

```{r avg for ea FRP}
avgQpcr <- qpcr %>%
group_by(FRP, trtmnt_tank) %>%
summarize(avg_sq = mean(sq_all.runs_mean, na.rm=TRUE), trtmnt_tank, sample_day, infection_status, maturity, sample_pos.neg) %>% 
distinct_all() %>%
filter(trtmnt_tank == "cold" | trtmnt_tank == "warm" | trtmnt_tank == "ambient")
```


```{r aggregate attempt, include = FALSE}
#aggregate(data = qpcr, cbind(mean(sq_all.runs_mean, na.rm=TRUE), trtmnt_tank, sample_day,  infection_status, maturity, sample_pos.neg) ~ FRP, FUN = mean, na.action = na.omit) + 
  #filter(trtmnt_tank == "cold" | trtmnt_tank == "warm" | trtmnt_tank == "ambient") +
  #filter(sample_day == 0 | sample_day == 2 | sample_day == 17))
```

```{r plots}
#treatment tank
trtmnt <- ggplot(avgQpcr, aes(x = avg_sq)) +
  geom_histogram(bins = 100) +
  scale_x_log10() +
  facet_grid(~trtmnt_tank)

#sample day
day <- ggplot(avgQpcr, aes(x = avg_sq)) +
  geom_histogram(bins = 100) +
  scale_x_log10() +
  facet_grid(~sample_day)

#infection status
infection <- ggplot(avgQpcr, aes(x = avg_sq)) +
  geom_histogram(bins = 100) +
  scale_x_log10() +
  facet_grid(~infection_status)

#maturity
maturity <- ggplot(avgQpcr, aes(x = avg_sq)) +
  geom_histogram(bins = 100) +
  scale_x_log10() +
  facet_grid(~maturity)

#sample negative or positive
ggplot(avgQpcr, aes(x = avg_sq)) +
  geom_histogram(bins = 100) +
  scale_x_log10() +
  facet_grid(~sample_pos.neg)
```

